client_id = "fda520a1fd68303eac7eebcd89f0ea88"
name = "cartd"
application_url = "https://cartd.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"

[access_scopes]
scopes = "write_products,read_products,write_discounts,read_orders"

[app_proxy]
url = "https://cartd.vercel.app/apps/supercartd"
subpath = "supercartd"
prefix = "apps"

[auth]
redirect_urls = [ "https://cartd.vercel.app/api/auth" ]
